<script setup lang="ts">
// No i18n for legal documents
</script>

<template>
  <BaseModal modal-name="privacyPolicy" title="Privacy Policy">
    <div class="text-sm space-y-4">
      <h3 class="text-lg font-semibold">
        Introduction
      </h3>
      <p>This Privacy Policy describes how Shadle ("we," "us," or "our") collects, uses, and protects information when you use our color-guessing puzzle game.</p>

      <h3 class="text-lg font-semibold">
        Data We Collect
      </h3>
      <p>We collect essential data necessary for the app's functionality:</p>
      <ul class="ml-4 list-disc list-inside">
        <li><strong>Player ID:</strong> A unique pseudo-anonymous identifier generated by the app and stored in your browser's localStorage. This helps track your game progress and history anonymously across sessions.</li>
        <li><strong>Game Attempts:</strong> Records of your puzzle attempts, including the puzzle ID, number of tries, completion status, and timestamps. This data is linked to your Player ID.</li>
        <li><strong>Push Notifications:</strong> If enabled, your Player ID, platform (iOS/Android/Web), and push subscription details (endpoint and encryption keys). This is used for sending notifications.</li>
        <li><strong>Puzzle Statistics:</strong> Aggregated, anonymized stats for puzzles (e.g., average tries, success rates) shared across all users.</li>
        <li><strong>Analytics Data:</strong> We use Google Analytics to collect information about how you use the app, such as pages visited, time spent, and interactions. This data is anonymized and helps us improve the app.</li>
      </ul>
      <p>We do not collect personally identifiable information such as your name, email, IP address, or location. We use browser localStorage for Player IDs and may use cookies via Google AdSense and Google Analytics for ads and analytics. You can manage cookies in your browser settings.</p>

      <p>This app is not intended for users under 13. We do not knowingly collect data from children.</p>

      <h3 class="text-lg font-semibold">
        How We Use Your Data
      </h3>
      <p>Our data processing is based on legitimate interest for app functionality and your consent for notifications/ads.</p>
      <ul class="ml-4 list-disc list-inside">
        <li>To provide game functionality, including saving progress and displaying history.</li>
        <li>To calculate and display puzzle statistics.</li>
        <li>To send push notifications if you opt-in.</li>
        <li>To improve the app and fix issues.</li>
      </ul>

      <h3 class="text-lg font-semibold">
        Data Sharing and Third Parties
      </h3>
      <p>We do not sell, trade, or share your data with third parties, except as described below:</p>
      <ul class="ml-4 list-disc list-inside">
        <li><strong>Google AdSense:</strong> We use Google AdSense to display ads. Google may collect data via cookies and similar technologies for ad targeting and measurement. This includes information about your device and browsing activity. Google's use of this data is governed by their Privacy Policy (available at <a href="https://policies.google.com/privacy" target="_blank" class="text-blue-500 underline">policies.google.com/privacy</a>). You can opt out of personalized ads by visiting <a href="https://adssettings.google.com" target="_blank" class="text-blue-500 underline">adssettings.google.com</a>.</li>
        <li><strong>Google Analytics:</strong> We use Google Analytics to analyze website traffic and user behavior. Google may collect data via cookies and similar technologies. This data is used to improve our service. Google's use of this data is governed by their Privacy Policy (available at <a href="https://policies.google.com/privacy" target="_blank" class="text-blue-500 underline">policies.google.com/privacy</a>). You can opt out of Google Analytics by installing the Google Analytics Opt-out Browser Add-on (available at <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" class="text-blue-500 underline">tools.google.com/dlpage/gaoptout</a>).</li>
        <li><strong>Hosting and Infrastructure:</strong> Data is stored on secure servers. We use Cloudflare as a content delivery network (CDN) to improve performance and security. Cloudflare may collect IP addresses and other technical data as part of their service. See Cloudflare's privacy policy at <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" class="text-blue-500 underline">www.cloudflare.com/privacypolicy</a>. We may use other cloud providers, but they do not access your data.</li>
      </ul>

      <h3 class="text-lg font-semibold">
        Data Retention
      </h3>
      <p>Game data is retained indefinitely to maintain your history and statistics. You can reset your data in the app settings, which generates a new Player ID.</p>

      <h3 class="text-lg font-semibold">
        Your Rights
      </h3>
      <p>Since we collect no personal data, traditional rights like access or deletion are limited. However:</p>
      <ul class="ml-4 list-disc list-inside">
        <li>You can reset your game data in Settings > Reset Memory.</li>
        <li>You can disable push notifications in your device settings.</li>
        <li>For AdSense cookies, use the opt-out links above.</li>
      </ul>

      <h3 class="text-lg font-semibold">
        Security
      </h3>
      <p>We implement reasonable security measures to protect your data, but no method is 100% secure.</p>

      <h3 class="text-lg font-semibold">
        Changes to This Policy
      </h3>
      <p>We may update this policy occasionally.</p>

      <h3 class="text-lg font-semibold">
        Contact Us
      </h3>
      <p>If you have questions, contact us at contact@shadle.app.</p>

      <p class="text-xs text-gray-500">
        Last updated: November 25, 2025
      </p>
    </div>
  </BaseModal>
</template>
